/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as VKeyImport } from './routes/v/$key'

// Create Virtual Routes

const ZipLazyImport = createFileRoute('/zip')()

// Create/Update Routes

const ZipLazyRoute = ZipLazyImport.update({
  path: '/zip',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/zip.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const VKeyRoute = VKeyImport.update({
  path: '/v/$key',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/zip': {
      preLoaderRoute: typeof ZipLazyImport
      parentRoute: typeof rootRoute
    }
    '/v/$key': {
      preLoaderRoute: typeof VKeyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ZipLazyRoute,
  VKeyRoute,
])

/* prettier-ignore-end */
