/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as VKeyImport } from './routes/v/$key'

// Create Virtual Routes

const ZipLazyImport = createFileRoute('/zip')()

// Create/Update Routes

const ZipLazyRoute = ZipLazyImport.update({
  id: '/zip',
  path: '/zip',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/zip.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const VKeyRoute = VKeyImport.update({
  id: '/v/$key',
  path: '/v/$key',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/zip': {
      id: '/zip'
      path: '/zip'
      fullPath: '/zip'
      preLoaderRoute: typeof ZipLazyImport
      parentRoute: typeof rootRoute
    }
    '/v/$key': {
      id: '/v/$key'
      path: '/v/$key'
      fullPath: '/v/$key'
      preLoaderRoute: typeof VKeyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/zip': typeof ZipLazyRoute
  '/v/$key': typeof VKeyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/zip': typeof ZipLazyRoute
  '/v/$key': typeof VKeyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/zip': typeof ZipLazyRoute
  '/v/$key': typeof VKeyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/zip' | '/v/$key'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/zip' | '/v/$key'
  id: '__root__' | '/' | '/zip' | '/v/$key'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ZipLazyRoute: typeof ZipLazyRoute
  VKeyRoute: typeof VKeyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ZipLazyRoute: ZipLazyRoute,
  VKeyRoute: VKeyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/zip",
        "/v/$key"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/zip": {
      "filePath": "zip.lazy.tsx"
    },
    "/v/$key": {
      "filePath": "v/$key.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
